env: 
  browser: true
  es6: true
  commonjs: true
  jest: true
  es2020: true

extends: ['plugin:react/recommended', 'airbnb-base']

parser: 'babel-eslint'

parserOptions: 
  ecmaFeatures: 
    jsx: true
  ecmaVersion: 11
  sourceType: module
  
plugins: ['react', 'jest']

settings: 
  react:
    version: 'detect'
