language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  webpack --mode development

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $travis
  local_dir: public
  on:
    branch: master